version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sushi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql            # 永続化ストレージ
      - ./my.conf:/etc/mysql/conf.d/my.cnf # カスタム設定ファイル
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 初期化スクリプト
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql # 初期データスクリプト
